from enum import Enum
import json
from pathlib import Path

from ninja_syntax import Writer

SCRIPTS_DIR = Path(__file__).parent


class BuildType(Enum):
    NORMAL = 1
    TESTS = 2
    OBJDIFFBUILD = 3
    BINARY_MATCHBUILD = 4


class BuildVersion(Enum):
    VER_008p = 0x00081
    VER_013 = 0x00130
    VER_013a = 0x00131
    VER_100 = 0x01000
    VER_101 = 0x01010
    VER_102 = 0x01020
    # 1.02a is the same binary as 1.02
    VER_102b = 0x01022
    VER_102c = 0x01023
    VER_102d = 0x01024
    # 1.02e is the same binary as 1.02d
    VER_102f = 0x01026
    VER_102g = 0x01027
    VER_102h = 0x01028


def configure(build_type, build_version, ver_suffix):
    with (SCRIPTS_DIR.parent / "build.ninja").open("w") as f:
        writer = Writer(f, width=120)
        writer.variable("ninja_required_version", "1.5")

        writer.variable("builddir", "build")

        writer.variable("cl", "cl.exe")
        cl_common_flags = "/MT /EHsc /G5 /Gs /DNDEBUG /Zi /I $builddir/autogenerated /I src /I 3rdparty/munit"

        if build_version == BuildVersion.VER_008p:
            cl_common_flags += (
                " /DBUILD_VERSION=0x00081 /DGAME_VERSION=0x0008 /DTRIALBUILD"
            )
        elif build_version == BuildVersion.VER_013:
            cl_common_flags += (
                " /DBUILD_VERSION=0x00130 /DGAME_VERSION=0x0013 /DTRIALBUILD"
            )
        elif build_version == BuildVersion.VER_013a:
            cl_common_flags += (
                " /DBUILD_VERSION=0x00131 /DGAME_VERSION=0x0013 /DTRIALBUILD"
            )
        elif build_version == BuildVersion.VER_100:
            cl_common_flags += " /DBUILD_VERSION=0x01000 /DGAME_VERSION=0x0100"
        elif build_version == BuildVersion.VER_101:
            cl_common_flags += " /DBUILD_VERSION=0x01010 /DGAME_VERSION=0x0101"
        elif build_version == BuildVersion.VER_102:
            cl_common_flags += " /DBUILD_VERSION=0x01020 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102b:
            cl_common_flags += " /DBUILD_VERSION=0x01022 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102c:
            cl_common_flags += " /DBUILD_VERSION=0x01023 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102d:
            cl_common_flags += " /DBUILD_VERSION=0x01024 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102f:
            cl_common_flags += " /DBUILD_VERSION=0x01026 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102g:
            cl_common_flags += " /DBUILD_VERSION=0x01027 /DGAME_VERSION=0x0102"
        elif build_version == BuildVersion.VER_102h:
            cl_common_flags += " /DBUILD_VERSION=0x01028 /DGAME_VERSION=0x0102"

        if build_type == BuildType.BINARY_MATCHBUILD:
            cl_common_flags += " /DBINARYMATCHBUILD"

        if (
            build_version != BuildVersion.VER_008p
            and build_version != BuildVersion.VER_013
            and build_version != BuildVersion.VER_013a
        ):
            cl_common_flags += " /GS"

        writer.variable("cl_common_flags", cl_common_flags)

        cl_flags = "$cl_common_flags /Op /Gy /GF /YX"
        if (
            build_version != BuildVersion.VER_008p
            and build_version != BuildVersion.VER_013
            and build_version != BuildVersion.VER_013a
        ):
            writer.variable("cl_flags", cl_flags + " /Od /Ob1")
        else:
            writer.variable("cl_flags", cl_flags + " /O2")
        writer.variable("cl_flags_pbg3", "$cl_common_flags /O2")

        writer.variable("rc", "rc.exe")
        writer.variable("link", "link.exe")

        th06_link_flags = "/subsystem:windows /machine:X86 /opt:win98 /incremental:no /opt:ref /opt:icf /map /mapinfo:exports /mapinfo:lines"

        writer.variable("msvc_deps_prefix", "Note: including file:")

        writer.rule(
            "cc",
            "$cl /nologo /showIncludes $cl_flags /Fp$out.pch /c $in /Fd$out.pdb /Fo$out",
            deps="msvc",
        )
        writer.rule("genglobals", "python scripts/generate_globals.py $in $out")
        writer.rule("rc", "$rc /fo $out $in")
        writer.rule(
            "link",
            "$link $link_flags /nologo /out:$out $in $link_libs",
        )
        writer.rule(
            "copyicon",
            'python -c "import shutil; import sys; shutil.copyfile(sys.argv[1], sys.argv[2])" $in $out',
        )
        writer.rule("extracticon", "python scripts/extract_icon.py --output $out")
        writer.rule(
            "geni18n",
            "python scripts/generate_i18n.py $in $out",
        )
        writer.rule(
            "rename_symbols",
            "python scripts/generate_objdiff_objs.py $in",
        )

        cxx_sources = [
            "AsciiManager",
            "Stage",
            "BombData",
            "EclManager",
            "EnemyEclInstr",
            "EffectManager",
            "Ending",
            "EnemyManager",
            "BulletManager",
            "Gui",
            "GameManager",
            "Global",
            "TextHelper",
            "ItemManager",
            "main",
            "MidiOutput",
            "Supervisor",
            "MusicRoom",
            "Player",
            "BulletData",
            "ReplayManager",
            "ResultScreen",
            "ScreenEffect",
            "SoundPlayer",
            "AnmManager",
            "MainMenu",
            "zwave",
        ]

        force_ob1_sources = set(["GameManager", "Supervisor", "MainMenu"])

        small_codegen_sources = set(
            [
                "GameManager",
                "Gui",
                "MainMenu",
                "MusicRoom",
                "Supervisor",
                "TextHelper",
                "ResultScreen",
            ]
        )

        no_intrin_sources = set(
            [
                "MainMenu",
                "TextHelper",
                "ResultScreen",
            ]
        )

        pbg3_sources = [
            "IPbg3Parser",
            "Pbg3Parser",
            "Pbg3Archive",
            "FileAbstraction",
        ]

        munit_sources = ["munit"]

        test_sources = [
            "tests",
            "test_Pbg3Archive",
        ]

        # TODO: might make more sense to work the other way around: generate
        # objdiff.json from the ninja.
        with open("objdiff.json") as f:
            objdiff_json = json.load(f)
        objdiff_deps = []
        for obj in objdiff_json.get("objects", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        for obj in objdiff_json.get("units", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        writer.build("objdiff", "phony", [], objdiff_deps)

        for rule in cxx_sources:
            variables = {"cl_flags": "$cl_flags"}
            if rule in small_codegen_sources:
                variables["cl_flags"] += " /Os"
            if rule in no_intrin_sources:
                variables["cl_flags"] += " /Oi-"
            else:
                variables["cl_flags"] += " /Oi"
            if rule in force_ob1_sources:
                variables["cl_flags"] += " /Ob1"

            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "src/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
                variables=variables,
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for rule in pbg3_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "src/pbg3/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
                variables={"cl_flags": "$cl_flags_pbg3"},
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for rule in munit_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "3rdparty/munit/" + rule + ".c",
            )

        for rule in test_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc",
                "tests/" + rule + ".cpp",
            )

        writer.build(
            "$builddir/globals.obj",
            "genglobals",
            inputs="config/globals.csv",
            implicit=["scripts/generate_globals.py"],
        )
        writer.build("$builddir/autogenerated/i18n.hpp", "geni18n", "src/i18n.tpl")
        if build_type == BuildType.BINARY_MATCHBUILD:
            writer.build("resources/original.ico", "extracticon")
            writer.build(
                "$builddir/icon.ico",
                "copyicon",
                "resources/original.ico",
                implicit="resources/original.ico",
            )
        else:
            writer.build("$builddir/icon.ico", "copyicon", "resources/placeholder.ico")
        writer.build(
            "$builddir/th06.res",
            "rc",
            inputs="resources/th06.rc",
            implicit="$builddir/icon.ico",
        )
        objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg3_sources]
            + ["$builddir/th06.res"]
        )

        th06_link_libs = "dinput8.lib dsound.lib d3d8.lib d3dx8.lib winmm.lib dxguid.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib odbc32.lib odbccp32.lib"

        # Original exe does not have PDB path
        if build_type != BuildType.BINARY_MATCHBUILD:
            th06_link_flags += " /debug /pdb:$builddir/th06" + ver_suffix + ".pdb"

        writer.build(
            "$builddir/th06" + ver_suffix + ".exe",
            "link",
            inputs=objfiles,
            variables={"link_libs": th06_link_libs, "link_flags": th06_link_flags},
        )

        test_objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in pbg3_sources]
            + ["$builddir/" + src + ".obj" for src in test_sources]
        )
        writer.build(
            "$builddir/th06-tests.exe",
            "link",
            inputs=test_objfiles + ["$builddir/munit.lib"],
            variables={
                "link_libs": th06_link_libs + " $builddir/munit.lib",
                "link_flags": "/pdb:$builddir/th06.pdb",
            },
        )

        writer.build(
            "$builddir/munit.lib",
            "link",
            inputs=["$builddir/" + s + ".obj" for s in munit_sources],
            variables={"link_flags": "/lib", "link_libs": ""},
        )

        writer.close()


if __name__ == "__main__":
    configure(BuildType.NORMAL, BuildVersion.VER_102h, "")
